blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/ncolesummers/idaho-data/discussions
    about: Ask questions and discuss ideas
  - name: 📖 Documentation
    url: https://github.com/ncolesummers/idaho-data/wiki
    about: Check our documentation first
  - name: 🔒 Security Issue
    url: https://github.com/ncolesummers/idaho-data/security/policy
    about: Please report security vulnerabilities responsibly